title: "Airband 125"
author: "somnusberg"
description: "Tis not too late to seak a newer world"
lang: "en"

# Page settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/
hide_title: false            # remove site heading in the header
post_footer: true            # show previous and next links at the end of each post

# Theme settings
dark_theme: false            # use the dark mode as default
dark_header: true            # keep the header dark
# style: minimal             # use a simpler style inspired by the minima theme

navigation:                  # (optional) site navigation in the header
  - index.html
  - posts.html
  - README.md
#  - Disk: "https://www.google.com"       # linking external sites is also supported

icons:                       # (optional) icons in the header, see http://fontawesome.com/icons
  envelope: "mailto:somnusberg@gmail.com"
#  facebook: "https://www.facebook.com/somnusberg"
  weibo: "https://weibo.com/3991698263/profile?topnav=1&wvr=6&is_all=1‚Äù

# Pagination
show_excerpts: false         # preview articles on the home page
paginate: 8                  # number of articles per page
excerpt_separator: "\n\n\n"  # indicate the end of the excerpt by two blank lines

comments:                    # embed disqus or isso comments
  gitalk: true
  gitalk_clientID: 'e3850747124fe740dd9e'
  gitalk_Secret: 'a5b8ec1d4c7729d904831d9c99aa7a1800d56826'
  gitalk_repo: 'somnusberg.github.io'
  gitalk_owner: 'somnusberg'
  gitalk_admin: 'somnusberg'
  distractionFreeMode: true

plugins:
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout
